### ISSUE TITLE
npm install 过程中出现问题

### ISSUE THREAD

**Issue by BigKongfuPanda** [duxianwei520/react#1]
提示的问题如下：
npm WARN deprecated babel-plugin-antd@0.5.1: babel-plugin-antd is renamed to babel-plugin-import
npm WARN deprecated babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package
npm WARN deprecated ghooks@1.3.2: Use npmjs.com/husky instead, see https://github.com/gtramontina/ghooks/issues/166

该怎么解决啊？

**Comment by duxianwei520** [comment]
亲，我今天更新了整个npm包，你直接down下来然后解压到当前文件夹就可以运行了，导致这个问题的，可能就是有些包过期了或者网络问题没下载下来

**Comment by BigKongfuPanda** [comment]
好的啊

在 2017-02-28 11:30:54，"肚皮" <notifications@github.com> 写道：


亲，我今天更新了整个npm包，你直接down下来然后解压到当前文件夹就可以运行了，导致这个问题的，可能就是有些包过期了或者网络问题没下载下来
