### ISSUE TITLE
跑步起来，npm run dev

### ISSUE THREAD

**Issue by ShuangDa1018** [duxianwei520/react#110]
PS D:\react\react-master> npm run dev

> react-admin@0.1.0 dev D:\tanshuang\react\react-master
> webpack-dev-server --config ./scripts/webpack.dev.config.js

events.js:292
      throw er; // Unhandled 'error' event

**Comment by ShuangDa1018** [comment]
> react-admin@0.1.0 dev D:\tanshuang\react\react-master
> webpack-dev-server --config ./scripts/webpack.dev.config.js

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:8888
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1498:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8888
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-admin@0.1.0 dev: `webpack-dev-server --config ./scripts/webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-admin@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TWX1039639\AppData\Roaming\npm-cache\_logs\2021-07-08T04_26_52_010Z-debug.log

**Comment by duxianwei520** [comment]
看提示好像是你自己的端口被占用了吧@ShuangDa1018
