### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by pfeducode** [duxianwei520/react#125]
一直报下面的错误，不知道为什么
![image](https://user-images.githubusercontent.com/100210045/210173075-4592121f-42e5-4be2-ad9c-692765670913.png)

**Comment by pfeducode** [comment]
![image](https://user-images.githubusercontent.com/100210045/211069732-124bbc0d-f126-43fb-b5d5-27ddf8a06a98.png)

**Comment by duxianwei520** [comment]
@pfeducode 估计是你的npm包没下载完全，试试挂全局的代理，我每次都是成功的，你这个问题很多人都提到过

**Comment by pfeducode** [comment]
> @pfeducode 估计是你的npm包没下载完全，试试挂全局的代理，我每次都是成功的，你这个问题很多人都提到过

挂全局的代理，你是说需要挂VPN吗
