### ISSUE TITLE
开启mock数据服务之后，还要做哪些才能让前台housemanage页面获取到数据呢？

### ISSUE THREAD

**Issue by ajnudnyy** [duxianwei520/react#13]
肚皮哥：
  两个服务我都打开了，为什么我的页面还是刷新不出数据来呢？

![fssd](https://user-images.githubusercontent.com/18208441/28856792-8cca0b34-7777-11e7-86f1-4ff411ce1741.png)

**Comment by ajnudnyy** [comment]
![df](https://user-images.githubusercontent.com/18208441/28857403-e7450984-777b-11e7-91d1-77f3a081e5bd.png)

**Comment by duxianwei520** [comment]
@ajnudnyy  是否有网络请求，亲应该是把开发者工具的network截图出来的呀，console里面看不到是否有发送异步请求的呀

**Comment by ajnudnyy** [comment]
![dsfds](https://user-images.githubusercontent.com/18208441/29017662-683f4bfa-7b8a-11e7-92ae-e274fc65d528.png)

![dsfsdf](https://user-images.githubusercontent.com/18208441/29018071-304aad64-7b8c-11e7-907a-5ac3ccc58d6a.png)


就是这样的

**Comment by duxianwei520** [comment]
@ajnudnyy   把network里面的消息截图，是这个部位
![image](https://user-images.githubusercontent.com/3249653/29062997-9f61827a-7c56-11e7-8097-b33aa666d86d.png)

**Comment by ajnudnyy** [comment]
这不是截图了吗？

**Comment by ajnudnyy** [comment]
我现在写了一些模块， 想打包扔到公司服务器上去， 但是敲了npm build 之后好像没反应啊？

**Comment by ajnudnyy** [comment]
哦， 请问你是蚂蚁金服团队里的吗？ 怎么用antd那么6，我这几天要用antd-mobile搭一个移动端， 但是怎么搭都搭建不了， 不知道怎么了

**Comment by ajnudnyy** [comment]
哦， 请问你是蚂蚁金服团队里的吗？ 怎么用antd那么6，我这几天要用antd-mobile搭一个移动端， 但是怎么搭都搭建不了， 不知道怎么了

我在github上找了一个搭建好了的，开发完了， 但是打包出来又不能用
