### ISSUE TITLE
关于登录、以及登录权限控制

### ISSUE THREAD

**Issue by GitVitality** [duxianwei520/react#17]
sessionStorage可以在客户端手动设置token值，如何做到严格的权限控制呢？

**Comment by duxianwei520** [comment]
@GitVitality  前端所做的任何限制，都只是表象上的，所以一定需要让后端来配合做操作，比如用户虽然可以通过手动设置session来进入页面，但是进入了其他需要请求数据的页面，都需要后端返回数据，后端会校验前端发送的session是否合法，不合法就跳出登录了呀，你想做得再严格点，用户每次跳转到新的路由，都去请求是否有权限的接口就行了嘛
