### ISSUE TITLE
使用css 的伪类时不支持

### ISSUE THREAD

**Issue by succulen-plants** [duxianwei520/react#27]
在js文件添加div   class为dd
import  './dd.css';
<div className="welcome">
        <div className="content">
          <h2 className="title">肚皮叔：行，我等你</h2>
          <div className="dd"></div>
        </div>
      </div>

dd.css  文件内容
.dd, .dd::before, .dd::after {
          position: absolute;
          top: 0;
          bottom: 0;
          left: 0;
          right: 0;
        }
         
        .dd {
          width: 200px;
          height: 200px;
          margin: auto;
          /*background: url("img/Button-White-Large.png") no-repeat 50%/70% rgba(0, 0, 0, 0.1);*/
          background: rgba(0, 0, 0, 0.1);
          color: #69ca62;
          box-shadow: inset 0 0 0 1px rgba(105, 202, 98, 0.5);
        }
        .dd::before, .dd::after {
          content: '';
          z-index: -1;
          margin: -5%;
          box-shadow: inset 0 0 0 2px;
          animation: clipMe 8s linear infinite;
        }
        .dd::before {
          animation-delay: -4s;
        }
        .dd:hover::after, .dd:hover::before {
          background-color: rgba(255, 0, 0, 0.3);
        }
         
        @keyframes clipMe {
          0%, 100% {
            clip: rect(0px, 220.0px, 2px, 0px);
          }
          25% {
            clip: rect(0px, 2px, 220.0px, 0px);
          }
          50% {
            clip: rect(218.0px, 220.0px, 220.0px, 0px);
          }
          75% {
            clip: rect(0px, 220.0px, 220.0px, 218.0px);
          }
        }  

这个例子在自己的项目中可以使用， 你的这个项目里不行， 测试过 对   ::before  等无法解析， 但是找不到webpack配置的问题

**Comment by duxianwei520** [comment]
@succulen-plants 我测试过了，伪类是支持的，肯定是你自己写的不对，before跟after都需要设置content的
![image](https://user-images.githubusercontent.com/3249653/34248997-07cae32a-e673-11e7-9f51-d742154d697b.png)
![image](https://user-images.githubusercontent.com/3249653/34249022-210bb3a0-e673-11e7-8a99-deda8e568b36.png)
