### ISSUE TITLE
请问一下这个项目弹出新页面效果如何实现的？

### ISSUE THREAD

**Issue by yourenA** [duxianwei520/react#3]
请问一下点击侧边栏，然后右边弹出新的页面。如果右边已经有页面，则跳到那个页面。这个效果事如何实现的，如何切换页面的时候如何保存数据

**Comment by duxianwei520** [comment]
左侧栏一行对应的是一个路由地址，在route里面都对应好了的，点击之后可以获取到当前项的url地址，然后路由跳转过去就可以了呀

**Comment by duxianwei520** [comment]
@yourenA 没什么问题我就关问题了呀
