### ISSUE TITLE
npm run build 打包后  routes里所有的js都会被单独打包到dist中

### ISSUE THREAD

**Issue by succulen-plants** [duxianwei520/react#30]
没弄明白什么地方导致这样的结果， 暂时不需要这样的打包配置

**Comment by duxianwei520** [comment]
@succulen-plants  routes里面的js默认是按照路由做了按需加载的，如果你不想用按需加载的话，那就跟route.js里面的APP这个component一样，不用getComponent加载，直接用component引入就好了

**Comment by succulen-plants** [comment]
好的，学习了， 谢谢
