### ISSUE TITLE
json 一直报错

### ISSUE THREAD

**Issue by haoLingLing** [duxianwei520/react#32]
![image](https://user-images.githubusercontent.com/25626661/35382041-13b3c9c6-01f9-11e8-89ce-72da7247be9e.png)
![image](https://user-images.githubusercontent.com/25626661/35382055-1f8c4c3c-01f9-11e8-9582-005c566d4beb.png)

导致一直报错 端口号改成一直就好

**Comment by hq229075284** [comment]
可以把报错信息贴一下么？ @haoLingLing

**Comment by xieminhui** [comment]
mock的端口应该跟你config一致的吧，不一致请求mock肯定出错了

**Comment by hq229075284** [comment]
global.$ctx指的是后端接口地址，这里$ctx配的是8000端口，而mock服务监听的是1111端口 @haoLingLing
