### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by benzcar** [duxianwei520/react#35]
安装依赖后，等陆不上，不知道什么问题
报错：：      TypeError: Failed to fetch
 #求指教
![tim 20180208163217](https://user-images.githubusercontent.com/25165037/35962822-c648ee8c-0ced-11e8-852f-1510f0d852f3.png)
![tim 20180208163203](https://user-images.githubusercontent.com/25165037/35962823-c6a04718-0ced-11e8-9cc4-bf027499317a.png)

**Comment by duxianwei520** [comment]
同学，这是个异步的请求，想登录进去主页面，可以在app/page/login.js里面把sessionStorage.setItem('token', 'dupi'); hashHistory.push('/')这两行代码的注释打开就可以进入主页面了，这不是bug@benzcar
