### ISSUE TITLE
提问关于react-router

### ISSUE THREAD

**Issue by AndyLIUMel** [duxianwei520/react#37]
我看官方说不应该直接用react-router, 而是用react-router-dom. 
那为什么这个repo用的是 core 呢？

**Comment by hq229075284** [comment]
我觉得因为升级router到v4后，路由被当成组件分布在其他组件内部，使得整个路由分散在各个组件中，不直观，所以只升级到v3，仍然保持静态路由的状态，可以使维护者更容易找到路由对应的组件

其次是v4提供的组件化、动态路由和新改进的一些匹配规则，在这里并没有太大的作用

如果仍然有什么疑问的话，欢迎留言， @AndyLIUMel 😃
