### ISSUE TITLE
路由怎么不用4.x？代码分割和懒加载的方式还是webpack2.x吗？

### ISSUE THREAD

**Issue by zhi3210happy** [duxianwei520/react#38]
RT

**Comment by hq229075284** [comment]
同 #37 类似的问题，代码分割仍然使用require.ensure，后面会考虑import加/** 注释 **/的形式

**Comment by wd2010** [comment]
我也在很久之前做了一个react服务端渲染的项目，使用的是import按需加载，解决了首屏白屏，代码分割，按需加载等功能，[https://github.com/wd2010/React-universal-ssr](https://github.com/wd2010/React-universal-ssr)，可以相互交流下
