### ISSUE TITLE
包没写进依赖

### ISSUE THREAD

**Issue by Leslie2014** [duxianwei520/react#4]
各种包缺失。。 request、classnames、lodash。

**Comment by duxianwei520** [comment]
@Leslie2014 npm依赖加载包没问题，我测试过，可能是因为有些npm包因为网络原因导致没下载成功，需要翻墙才能下载的，所以如果不行你就直接下载我上传到百度网盘的压缩过的包好了，因为已经很多个人表示运行成功了

**Comment by Leslie2014** [comment]
这个逻辑好像说不通吧。一个用户说我运行有问题，你跟他说别的用户都正常，所以不是问题。。 比如： `searchForm/index.js` 中就依赖了的 **lodash**，但是 `package.json` 里无论是 devDependencies 还是 dependencies 里中没有写。 ps: npm版本3.10.3，cnpm镜像下载，不存在网络问题。
