### ISSUE TITLE
本地json链接不上

### ISSUE THREAD

**Issue by annie-** [duxianwei520/react#40]
询问一下大神本地json为什么链接不上呢/需要修改申明配置活着我少了神马？

**Comment by annie-** [comment]
![image](https://user-images.githubusercontent.com/4263625/37874949-ea5d5358-306a-11e8-8bec-50c4ddae461d.png)
![13](https://user-images.githubusercontent.com/4263625/37874972-34be7814-306b-11e8-98fc-d073fa485e44.png)

**Comment by hq229075284** [comment]
mock服务有开么

**Comment by annie-** [comment]
打开了
![image](https://user-images.githubusercontent.com/4263625/37889182-c4d65092-30fd-11e8-8e35-546cf0cb58e5.png)

**Comment by hq229075284** [comment]
已更新接口请求的mock地址端口，请重新clone
