### ISSUE TITLE
登录密码账号是？？？

### ISSUE THREAD

**Issue by davychan1985** [duxianwei520/react#44]
如题

**Comment by charliecha1990** [comment]
Can anyone tells me why there is network error  every time I try to log in?

And what is the account and password btw?

2018-04-17 9:55 GMT-04:00 davychan1985 <notifications@github.com>:

**Comment by davychan1985** [comment]
顶

**Comment by One-boy** [comment]
@davychan1985 
你好，你需要启动服务端，在项目根目录下运行：node mock/http.js
再登录就好了。

**Comment by duxianwei520** [comment]
@davychan1985 更新下，已经可以登录了，用户名密码随意，其实就是更改下login.js的验证而已
