### ISSUE TITLE
不好意思，请管理员查看

### ISSUE THREAD

**Issue by baby179888** [duxianwei520/react#46]
我刚才问题这里  不小心提交了一个问题，随后就关闭了，但是现在每次我登陆githhub，库的列表里面还有你的库名字，怎么给去掉呢，不好意思

**Comment by One-boy** [comment]
@baby179888 不太明白你的意思，你是不是fork了这个库？

**Comment by baby179888** [comment]
@One-boy 操作步骤是->在Issuse里面提了一个问题，随后这个问题我已经解决了，我就把这个问题关闭了，现在我每次登陆github，左侧的仓库列表，里面就会显示我提问的仓库（以前那个仓库列表都是我自己创建的仓库名称）。
