### ISSUE TITLE
json请求失败

### ISSUE THREAD

**Issue by iEricOuyang** [duxianwei520/react#5]
请求时报错：“POST http://localhost:8080/mockapi/data.json net::ERR_CONNECTION_REFUSED”，路径被拼成了“localhost:8080”，应该是“localhost:3000”吧？

**Comment by duxianwei520** [comment]
@iEricOuyang 路径没错的，本地项目开启的端口是3000，但是再开启一个node服务不可能再是3000了，会冲突的啊，你可以看mockserver.js里面，listen的是8080端口，而不是3000

**Comment by wangcwang** [comment]
数据请求报错,没有数据显示啊!

**Comment by iEricOuyang** [comment]
一个项目要开两个服务？为啥？

**Comment by iEricOuyang** [comment]
@duxianwei520 明白了，项目跑起来要开两个服务，一个用node mockserver监听提供数据服务，另一个用npm start开启本地项目热点。

**Comment by duxianwei520** [comment]
@wangcwang 你看看network里面  有没有发出来网络请求，请求是否有回应的
