### ISSUE TITLE
npm install报错

### ISSUE THREAD

**Issue by lilegang1589** [duxianwei520/react#53]
npm WARN tarball tarball data for echarts@4.0.2 (sha1-xAXp5HmvmCODyK4rWUblLQWMYiA=) seems to be corrupted. Trying one more time.
npm ERR! path C:\work\git\react\node_modules\.staging\echarts-ad052c4b\dist\echarts-en.js.map
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\work\git\react\node_modules\.staging\echarts-ad052c4b\dist\echarts-en.js.map'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\work\git\react\node_modules\.staging\echarts-ad052c4b\dist\echarts-en.js.map'
npm ERR!     at Error (native)
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\work\git\react\node_modules\.staging\echarts-ad052c4b\dist\echarts-en.js.map'
npm ERR!        at Error (native)
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'C:\\work\\git\\react\\node_modules\\.staging\\echarts-ad052c4b\\dist\\echarts-en.js.map' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\work\\git\\react\\node_modules\\.staging\\echarts-ad052c4b\\dist\\echarts-en.js.map\'\n    at Error (native)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\work\\git\\react\\node_modules\\.staging\\echarts-ad052c4b\\dist\\echarts-en.js.map',
npm ERR!   parent: 'duxiaodu' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lileg\AppData\Roaming\npm-cache\_logs\2018-06-29T07_49_59_563Z-debug.log

15676 verbose stack Error: EPERM: operation not permitted, unlink 'C:\work\git\react\node_modules\.staging\echarts-ad052c4b\dist\echarts-en.js.map'
15676 verbose stack     at Error (native)
15677 verbose cwd C:\work\git\react
15678 verbose Windows_NT 10.0.16299
15679 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lileg\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
15680 verbose node v6.10.2
15681 verbose npm  v6.0.0
15682 error path C:\work\git\react\node_modules\.staging\echarts-ad052c4b\dist\echarts-en.js.map
15683 error code EPERM
15684 error errno -4048
15685 error syscall unlink
15686 error Error: EPERM: operation not permitted, unlink 'C:\work\git\react\node_modules\.staging\echarts-ad052c4b\dist\echarts-en.js.map'
15686 error     at Error (native)
15686 error  { Error: EPERM: operation not permitted, unlink 'C:\work\git\react\node_modules\.staging\echarts-ad052c4b\dist\echarts-en.js.map'
15686 error     at Error (native)
15686 error   cause:
15686 error    { Error: EPERM: operation not permitted, unlink 'C:\work\git\react\node_modules\.staging\echarts-ad052c4b\dist\echarts-en.js.map'
15686 error        at Error (native)
15686 error      errno: -4048,
15686 error      code: 'EPERM',
15686 error      syscall: 'unlink',
15686 error      path: 'C:\\work\\git\\react\\node_modules\\.staging\\echarts-ad052c4b\\dist\\echarts-en.js.map' },
15686 error   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\work\\git\\react\\node_modules\\.staging\\echarts-ad052c4b\\dist\\echarts-en.js.map\'\n    at Error (native)',
15686 error   errno: -4048,
15686 error   code: 'EPERM',
15686 error   syscall: 'unlink',
15686 error   path: 'C:\\work\\git\\react\\node_modules\\.staging\\echarts-ad052c4b\\dist\\echarts-en.js.map',
15686 error   parent: 'duxiaodu' }
15687 error The operation was rejected by your operating system.
15687 error It's possible that the file was already in use (by a text editor or antivirus),
15687 error or that you lack permissions to access it.
15687 error
15687 error If you believe this might be a permissions issue, please double-check the
15687 error permissions of the file and its containing directories, or try running
15687 error the command again as root/Administrator (though this is not recommended).
15688 verbose exit [ -4048, true ]

**Comment by duxianwei520** [comment]
@lilegang1589  我刚才特地在家里的电脑试过了，可以安装成功的，环境是win10，具体我就不贴图了，不知道你的环境怎样的

**Comment by lilegang1589** [comment]
我的也是win10，感觉是有些文件我没有权限去安装，我使用管理员身份安装也不行，node_modules文件夹里的依赖完全加不进来，没法处理

**Comment by duxianwei520** [comment]
@lilegang1589 试试安装在其他的非系统盘，试试更换npm源，还有不行就挂在个vpn，很可能是有些包没下载成功

**Comment by lilegang1589** [comment]
采用cnpm install 安装成功了，谢谢

**Comment by duxianwei520** [comment]
不客气，OK了就行
