### ISSUE TITLE
项目启动不老

### ISSUE THREAD

**Issue by kawinCheng** [duxianwei520/react#54]
![image](https://user-images.githubusercontent.com/20455249/42143170-626237ba-7de6-11e8-99a8-47740e27f8f6.png)

**Comment by kawinCheng** [comment]
启动不了

**Comment by duxianwei520** [comment]
@kawinCheng 建议先用原生的npm install下再试试，我觉得很有可能是因为cnpm下载的依赖包有问题导致启动不来的，我昨天在家重新clone下来然后现场npm install成功了

**Comment by duxianwei520** [comment]
@kawinCheng 建议先用原生的npm install下再试试，我觉得很有可能是因为cnpm下载的依赖包有问题导致启动不来的，我昨天在家重新clone下来然后现场npm install成功之后，再npm start没问题的，所以不知道你的环境是怎样的呢
