### ISSUE TITLE
权限管理模块咨询

### ISSUE THREAD

**Issue by ldwstyle** [duxianwei520/react#55]
请问该项目的权限管理模块只实现界面了，还是也实现功能了，再请教一下，react有没有权限解决方案，需求是这样的：一个任务是否有删除按钮是由多种权限控制的，比如创建者任何时候有删除按钮，执行者在任务完成后可以看到删除按钮，任务进行中看不到删除按钮，参与者任何时候不能看到删除按钮！

**Comment by duxianwei520** [comment]
@ldwstyle 亲，你这问题纯粹是个人业务的实现思路而已，跟react本身没关系，就算你用vue或者jQuery去做一样会遇到这个问题的，个人的理解是，你页面中的删除按钮，不仅是感觉权限控制，也根据用户的角色以及当前任务的状态来决定的，那就需要在页面多写几个逻辑判断来是否显示当前按钮即可
