### ISSUE TITLE
${process.cwd()}

### ISSUE THREAD

**Issue by succulen-plants** [duxianwei520/react#56]
npm run start:

ERROR in ./app/client.js
Module build failed: Error: /home/xiaoluo/dataVi/app/client.js: Cannot find any of these configuration files: ${process.cwd()}/webpack-test.config.js, webpack.config.js, webpack.config.babel.js

从webpack1  旧版本升级到现在的 webpack3

**Comment by succulen-plants** [comment]
问题找到了：.babelrc  文件中修改babel-plugin-webpack-alias 的config文件路径

**Comment by duxianwei520** [comment]
@succulen-plants  小罗菇凉厉害了
