### ISSUE TITLE
createAjaxAction 中的dispatch 如何传进去的？

### ISSUE THREAD

**Issue by guoweiwen** [duxianwei520/react#62]
这个问题好像还没有解决呀？怎么就close了？
还是不明白dispatch是怎么传进去 createAjaxAction方法的？能解答下吗？

**Comment by guoweiwen** [comment]
configs文件夹？没有这个文件夹呀，也没有common.js这个文件呀？

**Comment by duxianwei520** [comment]
@guoweiwen 在app/configs目录下面啊，里面的文件大部分都是配置文件或者公用模块的封装啊

**Comment by hq229075284** [comment]
createAjaxAction第一次执行的时候，返回一个函数，通过闭包把参数记录在闭包内，在返回的函数被调用时，又返回一个函数，假如叫thunk，这个thunk函数会当作入参传递到this.props.dispatch函数中，在这里使用了redux-thunk这个npm包，所以thunk函数会拿到两个入参，第一个就是redux的dispatch函数@guoweiwen

**Comment by guoweiwen** [comment]
> @guoweiwen 在app/configs目录下面啊，里面的文件大部分都是配置文件或者公用模块的封装啊

通过调试知道了，谢谢回答。

**Comment by guoweiwen** [comment]
> createAjaxAction第一次执行的时候，返回一个函数，通过闭包把参数记录在闭包内，在返回的函数被调用时，又返回一个函数，假如叫thunk，这个thunk函数会当作入参传递到this.props.dispatch函数中，在这里使用了redux-thunk这个npm包，所以thunk函数会拿到两个入参，第一个就是redux的dispatch函数@guoweiwen

谢谢，调试中发现了。
