### ISSUE TITLE
按照操作执行 npm start 报错，跑不起来

### ISSUE THREAD

**Issue by 02220** [duxianwei520/react#64]

**Comment by duxianwei520** [comment]
@02220 截图有报什么错的么

**Comment by duxianwei520** [comment]
@02220 我方才自己把node_modules删除重新npm install，完全没问题的，所以如果出问题报错，要么是你的网络有问题导致有些包没下载完，要么就是用的cnpm导致报错的，可以去下载我上传的压缩包直接解压即可https://github.com/duxianwei520/resource/blob/master/react/node_modules.rar
