### ISSUE TITLE
打开聊天室后，一直报用户名重复然后跳转到登录页，换个用户名也是一样

### ISSUE THREAD

**Issue by lkmdi** [duxianwei520/react#66]
![1552382652(1)](https://user-images.githubusercontent.com/31425436/54189020-e4509380-44eb-11e9-89d3-d16bfaa24102.png)

**Comment by duxianwei520** [comment]
我刚才重新安装了再打开，没有问题的啊，你是两次登录用的是同一个用户名的原因吧

**Comment by pfeducode** [comment]
> 我刚才重新安装了再打开，没有问题的啊，你是两次登录用的是同一个用户名的原因吧

我也是这个问题，是不是第一个账号没注销
