### ISSUE TITLE
createAjaxAction  中的dispatch 如何传进去的？

### ISSUE THREAD

**Issue by fanyongfeng** [duxianwei520/react#7]
export const createAjaxAction = (api, startAction, endAction) => (data, cb, reject) =>
  (dispatch) => {     //dispatch  怎么传进来的
    let respon
    startAction && dispatch(startAction())
    // eslint-disable-next-line no-param-reassign
    // 每个请求带上token
    const token = sessionStorage.getItem('token')
    if (token) {
      if (!data) {
        data = {}
      }
      data.token = token || null
    }
    data = isArray(data) ? data : [data]
    api(...data)
      .then(checkStatus) // eslint-disable-line no-use-before-define
      .then(response => response.json())
      .then((resp) => {
        respon = resp
        endAction && dispatch(endAction({ req: data, res: resp }))
      })
      .then(() => {
        if (respon.status === 1) {
          cb && cb(respon)
        } else {
          if (respon.errorCode == '101') {
            logOut()
          } else {
            if (typeof (reject) === 'function') {
              reject(respon)
            } else {
              message.error(respon.msg)
            }
          }
        }
      })
      .catch(catchError) // eslint-disable-line no-use-before-define
  }

然后在组件中调用  this.props.dispatch(fetchHouseCheckList({ currentPage: 1 }))
 在这里dispatch 不应该是一个action 么？
fetchHouseCheckList({ currentPage: 1 }) 返回的是一个function，
并且 上面中的 参数 dispatch 是如何传进去的呢？
蟹蟹。

**Comment by fanyongfeng** [comment]
function createThunkMiddleware(extraArgument) {
  return ({ dispatch, getState }) => next => action => {
    if (typeof action === 'function') {
      return action(dispatch, getState, extraArgument);
    }

    return next(action);
  };
}

const thunk = createThunkMiddleware();
thunk.withExtraArgument = createThunkMiddleware;

export default thunk;

**Comment by youngList** [comment]
createThunkMiddleware这个方法哪里找到的？

**Comment by youngList** [comment]
@hq229075284  ok,谢谢了
