### ISSUE TITLE
第一次登录进来左侧栏会挡住左边内容部分

### ISSUE THREAD

**Issue by Mathround** [duxianwei520/react#70]
浏览器：谷歌

第一次登录进来左侧栏会挡住左边内容部分，比如概览菜单里面的“示范页面”这四个字都被左侧栏给挡住了

**Comment by duxianwei520** [comment]
@Mathround 首先谢谢小兄弟的反馈，确实我是疏忽了一下，初始化的时候没有注意到，现在已经修复好并更新到git上
