### ISSUE TITLE
npm run dll报错

### ISSUE THREAD

**Issue by YHF7** [duxianwei520/react#74]
无法使用

**Comment by Crazymuyang** [comment]
切换node到8.7.0版本。
我一开始用最新稳定版的node也有问题

**Comment by hq229075284** [comment]
![image](https://user-images.githubusercontent.com/14305358/62825893-749f1b80-bbe5-11e9-8840-c77b07de6787.png)

**Comment by hq229075284** [comment]
@YHF7 检查下node_modules是否已经安装

**Comment by duxianwei520** [comment]
@YHF7 小老弟，2楼小哥说的是，如果你用最新版本的node，这个我没试过，但是8.7.0绝对没问题

**Comment by ren110** [comment]
![Uploading image.png…]()
切换node 8.7.0版本  @还是不行
