### ISSUE TITLE
移动端没有适配吗？

### ISSUE THREAD

**Issue by JingLMalan** [duxianwei520/react#75]
question as title

**Comment by duxianwei520** [comment]
毕竟做移动端的话，引入的ant design其实就已经不合适了，要用ant mobile，而且还需要加上过场动画，所以一般来说H5端会有另外一个类似的开箱即用的工具@JingLMalan

**Comment by duxianwei520** [comment]
https://github.com/duxianwei520/react-m   这里有移动端的可以参考一下

**Comment by JingLMalan** [comment]
Thank you.
