### ISSUE TITLE
项目运行不起来，报错

### ISSUE THREAD

**Issue by binsinger** [duxianwei520/react#76]
有遇到的？
![微信截图_20190902220346](https://user-images.githubusercontent.com/24548661/64119969-9dbe6080-cdcd-11e9-96e6-fb11ea8e541b.png)

**Comment by hq229075284** [comment]
clone之后，你有没有改动？

**Comment by duxianwei520** [comment]
@binsinger 你是直接npm install之后直接npm start报错的么，方便说下nodejs的版本的没
