### ISSUE TITLE
html-webpack-plugin在index.html文件中引用dll出错

### ISSUE THREAD

**Issue by lrmuyi** [duxianwei520/react#79]
![image](https://user-images.githubusercontent.com/25303760/65111044-0da72a80-da0d-11e9-9b52-d17fc3cb08ac.png)
大佬，请教个问题，打包的时候报这个错，应该是html-webpack-plugin在index.html文件中引用dll出错了，这个如何解决

**Comment by duxianwei520** [comment]
@lrmuyi 你把webpack.prod.config.js的多核压缩代码下面的compress那段注释掉看看，我是前几天才测试重新clone代码然后install再build都没报错的

**Comment by lrmuyi** [comment]
@duxianwei520 我把warnings配置提到output同级就不报错了，不确定是不是跟相关的依赖包版本有关
![image](https://user-images.githubusercontent.com/25303760/65211030-e4030780-dacf-11e9-9637-d1f84a1f90ff.png)

**Comment by duxianwei520** [comment]
@lrmuyi 解决了就好，我也把这行代码注释然后更新了
