### ISSUE TITLE
我也是报错，运行不了。麻烦您看一下哦。

### ISSUE THREAD

**Issue by Dawangdadada** [duxianwei520/react#8]
ERROR in ./app/history.js
Module not found: Error: Cannot resolve module 'history/lib/createHashHistory' i
n C:\Users\acer1\Desktop\react\app
 @ ./app/history.js 11:25-65

ERROR in ./app/components/searchForm/index.js
Module not found: Error: Cannot resolve module 'lodash' in C:\Users\acer1\Deskto
p\react\app\components\searchForm
 @ ./app/components/searchForm/index.js 135:14-31
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 541 kB [rendered]
        [0] ./~/._html-webpack-plugin@2.22.0@html-webpack-plugin/lib/loader.js!.
/app/index.html 1.38 kB {0} [built]
        [1] ./~/._lodash@4.17.4@lodash/lodash.js 540 kB {0} [built]
        [2] (webpack)/buildin/module.js 241 bytes {0} [built]
webpack: Failed to compile.

**Comment by fanyongfeng** [comment]
找不到包 lodash。   npm install  lodash

**Comment by duxianwei520** [comment]
@Dawangdadada  你试试楼上的  自己再安装下lodash试试  有些包可能没下载下来

**Comment by duxianwei520** [comment]
我今天把整个node_modules都删掉了 自己npm install之后再npm start是完全没问题的，亲没下载下来肯定是网络问题了咯
