### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by duruihong123** [duxianwei520/react#81]
下载后 npm install 不知道为什么老是报错
npm ERR! Unexpected end of JSON input while parsing near '...uia.com:8082/reposito'
npm WARN tarball tarball data for nise@1.4.6 (sha1-dsw5FZJQVq5sQF3YrV0SveVwwZ8=) seems to be corrupted. Trying one more time.
终止批处理操作吗(Y/N)? y

d:\工作\个人练习~\react-master\react-master>npm install
npm WARN tarball tarball data for pako@1.0.6 (sha1-AQEhG6pwxLykoPY/Igbpe3368lg=) seems to be corrupted. Trying one more time.
npm WARN The package babel-plugin-transform-decorators-legacy is included as both a dev and production dependency.

npm ERR! Unexpected end of JSON input while parsing near '...-packages","tmp":"tmp'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2019-11-11T08_52_23_255Z-debug.log

**Comment by duruihong123** [comment]
运行起来了，就是登陆报错

**Comment by duxianwei520** [comment]
登录报错，是不是没有启动mockjs的服务的呢@duruihong123 ？

**Comment by duruihong123** [comment]
你好，我运行起来后，登录不上呢发自我的华为手机-------- 原始邮件 --------发件人： 肚皮 <notifications@github.com>日期： 2019年11月14日周四 晚上8:21收件人： duxianwei520/react <react@noreply.github.com>抄送： duruihong123 <13811979394@163.com>, Mention <mention@noreply.github.com>主    题： Re: [duxianwei520/react] 运行不起来 (#81)登录报错，是不是没有启动mockjs的服务的呢@duruihong123 ？

**Comment by duxianwei520** [comment]
@duruihong123 是什么类型的报错呢，网络错误还是怎么的，方便给下截图的么

**Comment by duruihong123** [comment]
在 2019-11-18 10:15:27，"肚皮" <notifications@github.com> 写道：


@duruihong123 是什么类型的报错呢，网络错误还是怎么的，方便给下截图的么

**Comment by duruihong123** [comment]
网络错误，login接口显示404

在 2019-11-18 10:15:27，"肚皮" <notifications@github.com> 写道：


@duruihong123 是什么类型的报错呢，网络错误还是怎么的，方便给下截图的么

**Comment by duxianwei520** [comment]
怎么会，我刚启动了，npm start默认是会启动http服务和一个模拟接口的服务，你试试看分别启动npm run dev和npm run mock两个命令再试试@duruihong123

**Comment by duruihong123** [comment]
好的，好的

在 2019-11-20 14:30:56，"肚皮" <notifications@github.com> 写道：


怎么会，我刚启动了，npm start默认是会启动http服务和一个模拟接口的服务，你试试看分别启动npm run dev和npm run mock两个命令再试试@duruihong123

**Comment by duruihong123** [comment]
还是不行呢，我npm start 和分开 npm run 运行，都是报同样的错误




在 2019-11-20 14:30:56，"肚皮" <notifications@github.com> 写道：


怎么会，我刚启动了，npm start默认是会启动http服务和一个模拟接口的服务，你试试看分别启动npm run dev和npm run mock两个命令再试试@duruihong123

**Comment by duruihong123** [comment]
我试了试，不好使，截图那种

**Comment by duxianwei520** [comment]
@duruihong123 你可以附件里面带一张截图看看效果的么，因为这样子的问题很多朋友都提过，基本都是同样类似的问题

**Comment by duruihong123** [comment]
好的发自我的华为手机-------- 原始邮件 --------发件人： 肚皮 <notifications@github.com>日期： 2019年11月26日周二 下午3:32收件人： duxianwei520/react <react@noreply.github.com>抄送： duruihong123 <13811979394@163.com>, Mention <mention@noreply.github.com>主    题： Re: [duxianwei520/react] 运行不起来 (#81)@duruihong123 你可以附件里面带一张截图看看效果的么，因为这样子的问题很多朋友都提过，基本都是同样类似的问题
