### ISSUE TITLE
cnpm run dll告警 为啥子

### ISSUE THREAD

**Issue by juedefenqi** [duxianwei520/react#82]
D:\my\react-master>"node"  "D:\my\react-master\node_modules\.bin\\..\_webpack@3.10.0@webpack\bin\webpack.js" --config ./scripts/webpack.dll.config.js
Hash: f5d5799a3c4bf12d5ed7
Version: webpack 3.10.0
Time: 1993ms
        Asset    Size  Chunks                    Chunk Names
vendor.dll.js  660 kB       0  [emitted]  [big]  vendor
 redux.dll.js  115 kB       1  [emitted]         redux
  [59] (webpack)/buildin/global.js 509 bytes {0} {1} [built]
 [186] dll vendor 12 bytes {0} [built]
 [441] dll redux 12 bytes {1} [built]
 [451] (webpack)/buildin/harmony-module.js 596 bytes {1} [built]
    + 467 hidden modules

ERROR in Encountered an error while minifying redux.dll.js:
`warnings` is not a supported option

ERROR in Encountered an error while minifying vendor.dll.js:
`warnings` is not a supported option

**Comment by hq229075284** [comment]
我跑了一边发现并没有警告，可否告知你node_modules中安装的uglify-js、uglify-es、webpack-parallel-uglify-plugin这些依赖的版本？

![2019-11-21 22-53-24 的屏幕截图](https://user-images.githubusercontent.com/14305358/69349241-65367080-0cb2-11ea-8365-f81517f13e5c.png)

**Comment by duxianwei520** [comment]
@juedefenqi 不是很建议用cnpm，用npm你不能安装么
