### ISSUE TITLE
启动报错了！

### ISSUE THREAD

**Issue by xiaomaoaaa** [duxianwei520/react#87]
![image](https://user-images.githubusercontent.com/16348275/72135993-b74a6700-33c2-11ea-8ed3-b1a91c89e0df.png)

**Comment by duxianwei520** [comment]
@xiaomaoaaa 很可能是你本地的网络不行，导致有些依赖的npm包没下载完成导致启动不起来，很多人问这样子的问题了

**Comment by xiaomaoaaa** [comment]
webpack.base.config.js 的插件HappyPack和rules的css加载器有冲突 我注释 掉 // 'happypack/loader?id=happyStyle', 就好了

**Comment by duxianwei520** [comment]
不应该啊，我本地用得好好的，没什么问题

**Comment by FengYangLiu** [comment]
@xiaomaoaaa 你做了什么操作导致报错的？

**Comment by xiaomaoaaa** [comment]
@FengYangLiu  我就下载下来 启动的时候就报错了 ，没做什么操作，要么就是有依赖版本过低  （我看报错是 happypack和MiniCssExtractPlugin有冲突）

**Comment by molvshan** [comment]
我遇到了一模一样的问题，但是光注释掉css的happypack loader是不行的，还得手动用postcss-loader、less-loader、css-loader替换happypac loader
