### ISSUE TITLE
ERROR in Cannot find module '../../modules/es6.string.iterator'

### ISSUE THREAD

**Issue by xxmiao** [duxianwei520/react#9]
![image](https://user-images.githubusercontent.com/23732185/27730298-4d224756-5dbb-11e7-8f9a-8c15c96c6251.png)
这个是不是少装了什么模块？
我运行cnpm install es6.string.iterator之后还是没有用哦
求指导一下

**Comment by xxmiao** [comment]
补充一下：
这个错误是运行npm start之后报的~

**Comment by xxmiao** [comment]
运行cnpm install es6 也米有用~

**Comment by duxianwei520** [comment]
有尝试过我上传的压缩包么@xxmiao

**Comment by xxmiao** [comment]
![image](https://user-images.githubusercontent.com/23732185/27782960-ff9d18c8-6006-11e7-966f-31ad74259c0c.png)
下载你的压缩包之后没有之前说的问题了，可以跑起来，页面如上。
但是点击这些下一页，或者查看按钮，都没有反应。

**Comment by xxmiao** [comment]
@duxianwei520

**Comment by duxianwei520** [comment]
这些查看的按钮链接  是要你自己添加功能的呀，基本工程跑起来了，后面修行就靠个人了呀
