### ISSUE TITLE
请求地址

### ISSUE THREAD

**Issue by agnij** [duxianwei520/react#91]
http://[2409:8970:ab0:973a:2576:b547:33ca:9613]:8888/
报error

**Comment by a869057476** [comment]
+1

**Comment by a869057476** [comment]
> http://[2409:8970:ab0:973a:2576:b547:33ca:9613]:8888/
> 报error

要用npm start启动，npm run dev 的话会报错

**Comment by duxianwei520** [comment]
@agnij @a869057476 可能是我本地nodejs获取本机ip的方式太简单粗暴了导致获取本机地址错误，写了一个更精确的获取本机ip地址的方法，今天更新上去应该就不会出这个乱码的问题了
