### ISSUE TITLE
你好，配置了动态链接库，不是很懂。

### ISSUE THREAD

**Issue by xiaoyongchen** [duxianwei520/react#93]
你好，配置了动态链接库，是不是每次打包都需要，npm run dll,之后在npm run build,
nginx配置怎么样的。
“prod”: 'npm run build & npm run dll' 
需要这样配置吗

**Comment by duxianwei520** [comment]
如果dll没有更新的话，那么就不用每次都run dll了，直接run build即可 @xiaoyongchen
