### ISSUE TITLE
webpack问题

### ISSUE THREAD

**Issue by genaller** [duxianwei520/react#94]
不是很了解react生态,使用vue可以不需要配置原生webpack,但是这个项目全是原生webpack配置,react没有相关脚手架吗?还是reacter都用原生webpack结合react开发

**Comment by duxianwei520** [comment]
@genaller react也有类似vue那样的官方脚手架，叫做create-react-app，封装好了大部分的比较重要的周边功能，uni-app是阿里的类似的脚手架，区别无非是侧重点不一样，多用一下底层的配置，可以提高自己对周边生态的认识，用得好了，还可以针对自己公司的项目做出特定的优化，这何尝不是一种提高呢

**Comment by genaller** [comment]
respect
